### ISSUE TITLE
Omit device name prefix on SHDR keys

### ISSUE THREAD

**Issue by scottmwyant** [Ladder99/fanuc-driver#100]
Not sure I found the right line but I think I'm close.  I believe MTConnect.NET adapter(s) should not be sending the device name prefix on the key.  It's a good option in some cases, but since Fanuc Driver spawns adapters dynamically, each machine will always get its own adapter, so the adapter/device mapping is best controlled through the agent.cfg file.
  
https://github.com/Ladder99/fanuc-driver/blob/ece59d34c40fbca649e0f5ee6330397aa82e6840/fanuc/transports/SHDR.cs#L202

**Comment by MRIIOT** [comment]
Has this been addressed by passing in a YAML NULL ?

https://github.com/Ladder99/fanuc-driver/blob/d538eefe789b73757ca6127cba582e8f369bf049/examples/windows/config.machines.yml#L317
