### ISSUE TITLE
Fanuc Driver code has been run through visual studio code in ubuntu 20.04. I got the issue Dll not found exception. can you please guide me to register the focus library dlls in ubuntu 20.04.  

### ISSUE THREAD

**Issue by ajenita** [Ladder99/fanuc-driver#104]
Exception thrown: 'System.DllNotFoundException' in fanuc.dll: 'Unable to load shared library 'FWLIB32.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: /snap/dotnet-sdk/226/shared/Microsoft.NETCore.App/7.0.13/FWLIB32.dll.so: cannot open shared object file: No such file or directory /home/edgegateway/ladder99/fanuc/fanuc-driver/fanuc/bin/Debug/net7.0/FWLIB32.dll.so: cannot open shared object file: No such file or directory /snap/dotnet-sdk/226/shared/Microsoft.NETCore.App/7.0.13/libFWLIB32.dll.so: cannot open shared object file: No such file or directory /home/edgegateway/ladder99/fanuc/fanuc-driver/fanuc/bin/Debug/net7.0/libFWLIB32.dll.so: cannot open shared object file: No such file or directory /snap/dotnet-sdk/226/shared/Microsoft.NETCore.App/7.0.13/FWLIB32.dll: cannot open shared object file: No such file or directory /home/edgegateway/ladder99/fanuc/fanuc-driver/fanuc/bin/Debug/net7.0/FWLIB32.dll: cannot open shared object file: No such file or directory /snap/dotnet-sdk/226/shared/Microsoft.NETCore.App/7.0.13/libFWLIB32.dll: cannot open shared object file: No such file or directory /home/edgegateway/ladder99/fanuc/fanuc-driver/fanuc/bin/Debug/net7.0/libFWLIB32.dll: cannot open shared object file: No such file or directory'

**Comment by MRIIOT** [comment]
`FWLIB32.dll` is a Windows library.  To build on Linux you have to use the `.so` libraries.
