### ISSUE TITLE
Compare traffic on-the-wire with focas2.log data.

### ISSUE THREAD

**Issue by MRIIOT** [Ladder99/fanuc-driver#19]
> > > focas2.log is a Linux only log from the Fanuc library. We have no control over it.
> > > `public static extern short cnc_startupprocess(long level, string filename);`
> > 
> > I see. But could you not catch the output prior to writing it to file? I know, this is not _that_ important, but it’s nice to have. wink
> 
> It looks like it would be helpful for reversing the protocol on the wire.

Indeed it would be useful for that. :wink:

_Originally posted by @tukusejssirs in https://github.com/Ladder99/fanuc-driver/issues/4#issuecomment-864390147_

**Comment by tukusejssirs** [comment]
@MRIIOT, I don’t mind marking this issue as `wontfix`, but what is the reason? Especially, what’s the reason for the `security` label?

**Comment by MRIIOT** [comment]
Time and priority.  Unless we wanted to reverse the Focas protocol.
