### ISSUE TITLE
Error when installing using docker

### ISSUE THREAD

**Issue by alexmc1510** [Ladder99/fanuc-driver#23]
Hello, 
I have followed mentioned steps in the installation guide for docker armv7 and aarch64 but I receive following error:
 => [base 2/2] WORKDIR /app                                                                                       12.1s
 => [final 1/5] WORKDIR /app                                                                                       0.2s
 => [build 2/7] WORKDIR /src                                                                                       7.6s
 => [build 3/7] COPY [fanuc/fanuc.csproj, fanuc/]                                                                  0.1s
 => ERROR [build 4/7] RUN dotnet restore "fanuc/fanuc.csproj"                                                      0.8s
------
 > [build 4/7] RUN dotnet restore "fanuc/fanuc.csproj":
#12 0.715 A fatal error occurred, the folder [/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders
------
executor failed running [/bin/sh -c dotnet restore "fanuc/fanuc.csproj"]: exit code: 131

Would you be so kind as to provide the image as release so it will be easier to install it?
I am using docker engine running in Windows 10 host.

Thanks in advance.

Regards,

**Comment by MRIIOT** [comment]
https://hub.docker.com/r/ladder99/fanuc-driver/tags
