### ISSUE TITLE
docs: .NET Core SDK installation on Linux

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#29]
I could provide this information to the [docs](https://docs.ladder99.com/en/drivers/fanuc-driver#linux-x64) if you provide me access to your Wiki.js instance. I could also improve some other stuff in the docs (of course, I’ll ask you before changing some major stuff), but I don’t say I’ll be working on this 24/7. :wink:

Are you interested?

**Comment by MRIIOT** [comment]
@tukusejssirs you can log in with your github to https://docs.ladder99.com/.  When you do I will make you editor.

**Comment by tukusejssirs** [comment]
Yes, I’m. wink:

**Comment by MRIIOT** [comment]
@tukusejssirs you have permission to edit docs.

**Comment by tukusejssirs** [comment]
Thanks! 🙏

**Comment by tukusejssirs** [comment]
I wanted to edit the [Wiki](https://docs.ladder99.com/en/drivers/fanuc-driver), but it seems like I cannot edit the page (I can create a new one though).

**Comment by MRIIOT** [comment]
> I wanted to edit the [Wiki](https://docs.ladder99.com/en/drivers/fanuc-driver), but it seems like I cannot edit the page (I can create a new one though).

Are you sure?  I have my Github user in the same group as you and I can edit and save.

**Comment by tukusejssirs** [comment]
Well, there should an edit (pencil) floating button in bottom right corner, but I have button there.

**Comment by tukusejssirs** [comment]
I didn’t have that edit button there (only the add button) until now (I checked that right after you posted your comment). Now I have the edit button in the top panel. Strange.
