### ISSUE TITLE
What is the value of alarm code (`alm_no`) when it is `-1`?

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#31]
According the docs for [`cnc_rdalmmsg2`](https://docs.ladder99.com/focas-api/misc/cnc_rdalmmsg2.xml), alarm code (`alm_no`) can from interval `0-31` (`20-31` not being used) or `-1`. I have no idea when `-1` is used, but when it is used, what is the value of `state.data.alarms[].alm_no`? Is it empty or `-1`?

**Comment by MRIIOT** [comment]
alarm number -1 is not valid and will be removed from output.
