### ISSUE TITLE
Alarms: how to interprete `axis`?

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#32]
According to the docs for [`cnc_rdalmmsg2`](https://docs.ladder99.com/focas-api/misc/cnc_rdalmmsg2.xml):

> Axis number is stored. (1 to maximum controlled axes number)
> As for the none axis-type alarm, it is 0.

As I understand it, it is:
- `0` for alarms not related to axis;
- positive integer, which the numeric ID of an axis:
  - therefore the order of axis in `[fanuc/{machine-id}/sys_info/{path}].state.data.axes[] is important and I need to store it; the `name`, `suffix` and `path` is not sufficient to indentify an axis.

Do I get it right?

**Comment by MRIIOT** [comment]
What I would prefer is to read the alarms, and include them within each axis.

`fanuc/{machine-id}/alarms/1/X`, `fanuc/{machine-id}/alarms/1/Y`, etc.

**Comment by MRIIOT** [comment]
> therefore the order of axis in [fanuc/{machine-id}/sys_info/{path}].state.data.axes[] is important and I need to store it; the name, suffixandpath` is not sufficient to indentify an axis.

We already walk the axes.

https://github.com/Ladder99/fanuc-driver/blob/12301dad1ca31ccb6e3dafcfcfbdf13bfede95c2/fanuc/collectors/Basic03.cs#L131

**Comment by tukusejssirs** [comment]
> What I would prefer is to read the alarms, and include them within each axis.
> 
> `fanuc/{machine-id}/alarms/1/X`, `fanuc/{machine-id}/alarms/1/Y`, etc.
> 
> And non-axis alarms `fanuc/{machine-id}/alarms/1`, `fanuc/{machine-id}/alarms/2`.

Based on what I’ve already suggested in [this comment](https://github.com/Ladder99/fanuc-driver/issues/48#issuecomment-1027304072), I suggest to create a separate topic for all alarms. In that comment, however, I didn’t consider the axes or paths, but I would simply add another property; like so:

```typescript
alarms = [
  {
    code: number,
    type: 'info' | 'pmc' | 'common' | 'program' | 'system',
    level: 'info' | 'warning' | 'error',
    path: number,
    axis: number,
    message: string
  }
]
```

**Comment by MRIIOT** [comment]
> I suggest to create a separate topic for all alarms

Why not use the topic structure that loosely represents the physical composition of a CNC?

**Comment by tukusejssirs** [comment]
Well, actually, it does no really matter, as I could parse the topic and get all the required data (path and axis) and do with them whatever I wish. I’ll be somewhat easier for process the `alarms` object only (no need to regex match the topic). :wink:

I was thinking from my app point of view how to store the alarms data into DB and then visualise it. I think I’d put all alarms (and messages) of a machine into a single table with the suggested `alarms` object peoperties as columns.

That said, do as you wish / as it is easier for you to code it / as you think it is the best way to code it from `fanuc-driver` point of view.

**Comment by MRIIOT** [comment]
> Well, actually, it does no really matter, as I could parse the topic and get all the required data (path and axis) and do with them whatever I wish. I’ll be somewhat easier for process the `alarms` object only (no need to regex match the topic). 😉
> 
> I was thinking from my app point of view how to store the alarms data into DB and then visualise it. I think I’d put all alarms (and messages) of a machine into a single table with the suggested `alarms` object peoperties as columns.
> 
> That said, do as you wish / as it is easier for you to code it / as you think it is the best way to code it from `fanuc-driver` point of view.

https://github.com/Ladder99/fanuc-driver/blob/731f03b71f08015787c3b1f23f2ac40fafa17856/fanuc/veneers/AxisData.cs#L88-L93

**Comment by MRIIOT** [comment]
Alarm type decoded for each series.

https://github.com/Ladder99/fanuc-driver/blob/f9cb5bc9273e10613f940cd6e2e895ee45c56991/fanuc/veneers/AlarmsSeries.cs#L19-L29

**Comment by tukusejssirs** [comment]
> Alarm type decoded for each series.

It looks good! 🙏

All I need to do is to assign alarm texts to codes from thw maps, right? However, where does `PS100` for 16i comes from? I could not find it at [`cnc_rdalminfo`](https://www.inventcom.net/fanuc-focas-library/misc/cnc_rdalminfo) or [`cnc_rdalminfo2`](https://www.inventcom.net/fanuc-focas-library/misc/cnc_rdalminfo2).

> https://github.com/Ladder99/fanuc-driver/blob/731f03b71f08015787c3b1f23f2ac40fafa17856/fanuc/veneers/AxisData.cs#L88-L93

I’m a bit lost: what should those items mean? The `type` from [this comment of mine[(https://github.com/Ladder99/fanuc-driver/issues/32#issuecomment-1027341381)?

**Comment by MRIIOT** [comment]
> All I need to do is to assign alarm texts to codes from thw maps, right?

Nope, this automatically happens for the alarms observation.

https://github.com/Ladder99/fanuc-driver/blob/f9cb5bc9273e10613f940cd6e2e895ee45c56991/fanuc/veneers/AlarmsSeries.cs#L53-L60

> I’m a bit lost: what should those items mean?

The `alarms` property on the axis just calls out the conditions of overtravel, overheat, and servo.  This is separate from the entire list of alarms in the alarms observation.
