### ISSUE TITLE
Localised alarms

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#33]
According to the docs of [`cnc_rdopmsg2`](https://docs.ladder99.com/focas-api/misc/cnc_rdopmsg2.xml):

The message is acquired in the following character-codes.
>
> English 	          : 	ASCII
> Japanese 	          : 	Shift-JIS
> Simplified Chinese 	: 	Shift-JIS
> Traditional Chinese : 	GB2312
> Korean 	            : 	Code Page 949
> Cyrillic 	          : 	Code Page 1251
> Turkish 	          : 	Code Page 1254
> Others European 	  : 	Western Europe
>
> 1. Korean cannot be correctly acquired with FOCAS2/Ethernet.(Except 30i-B, 0i-D/F and PMi-A)
> 2. Refer to "APPENDIX I Central & East European Character Code", "APPENDIX J West European Character Code List" of "C Language Executor PROGRAMMING MANUAL" for Western Europe code.

Can we get a localised (alarm/message) text? Or even better: can we get a list of what languages are available and configure what languages the text should be gathered?

I don’t say this is a very important issue, but it might be a good for the end-users (managers, production, maintainance, …). Of course, if I understand the docs the right way. :wink:

**Comment by MRIIOT** [comment]
It appears that correct encoding needs to be applied, depending on the localization.  This can be defined in config, once I have examples of non-English operator messages.
