### ISSUE TITLE
Alarms/messages: Publish a message when an alarm/message is cleared.

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#34]
Related: [#13 (comment)](https://github.com/Ladder99/fanuc-driver/issues/13#issuecomment-891919189)

---

It’d be awesome if `fanuc-driver` publishes a new message (`fanuc/{machine}/message1`, `fanuc/{machine}/message2`, `fanuc/{machine}/alarms`, `fanuc/{machine}/alarms2`) whenever at least one alarm/message is cleared. Basically, this is exactly how event in MTConnect work (although still a bit differently). Without implementation of this, we cannot tell when an alarm/message is cleared.

We talked about this, but I am not sure if you have already implemented this.

**Comment by MRIIOT** [comment]
Alarm is removed from list and list is republished because it changed.
