### ISSUE TITLE
Gather stack lights data

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#37]
Related #21, #4

---

It would be awesome if we would gather the stack lights status (if the colours are on or off).

ATM I am not at the machines (I’ll be next week), but based on the photos I took from the Fanuc screens, the table below contains all the possible numbers of the individual colours from the ladder diagram on the machines I have access to.

| Green   | Yellow  | Red     |
|:--------|:--------|:--------|
| Y0002.4 | Y0002.3 | Y0002.2 |
| ST.L    | AL.L3   | AL.L1   |
| ST.L    | IN.L.Y  | AL.L1   |
| Y0006.5 | Y0004.3 | Y0004.2 |
| Y0022.3 | Y0022.4 | Y0022.5 |

If you need the machine vendors/models and/or whatever, just ask for it (I can get the info next week), however note that the numbers are not the same across machine vendors nor accross model series of the same vendor).

#### Implementation suggestions

- It might be a good idea to provide these three values as a single topic (e.g. `fanuc/{machine}/light_indicator`), e.g.: `{data: {green: true, yellow: false, red: false}}`.
- Each value could be a Boolean value.
- Initial/retained data should contain all values, then only the delta should be published (e.g. when `green` turns off and `yellow` turns on → `{data: {green: false, yellow: true}}`).
- When the machine is off, all colours should be turned off (and the delta values would be sent, regardless what colours were on while the machine was powering off).

**Comment by MRIIOT** [comment]
Sure, we could make a veneer for this.
I think this is where a Lua collector would make sense since it does not require a recompile and the PMC tags are vendor implementation specific.
The "report by exception" requirement is also possible, we just have to manage the data differently inside the veneer.

**Comment by MRIIOT** [comment]
We also need the address type and number for each one of these https://docs.ladder99.com/focas-api/pmc/pmc_rdpmcrng.xml.

I can assume that Y2.2 is second bit of address 2 of type Y, but I do not know what AL.L3 is.

**Comment by MRIIOT** [comment]
Supported as of https://github.com/Ladder99/fanuc-driver/commit/02373bdf491f22e59e1a38c3350c01337e64768a.

https://github.com/Ladder99/fanuc-driver/blob/02373bdf491f22e59e1a38c3350c01337e64768a/examples/windows/config.machines.yml#L206-L270

**Comment by MRIIOT** [comment]
Next Docker build should happen next week.

**Comment by smtpl-iiotian** [comment]
@MRIIOT, the generated devices.xml doesn't has the above macro and pmc variables. I am able to see macro and pmc data being fetched in the trace log. 
Please guide how and where to add macro variables in the generated devices.xml

**Comment by smtpl-iiotian** [comment]
@MRIIOT kindly reply how to get macro data in devices.xml.
