### ISSUE TITLE
Gather production data

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#38]
Related: #21, #4

---

I’d like to gather production, i.e. any and all information of the current production on a particular machine.

It could include the following information:

- number of produced pieces:

> Something like this? I don't remember if these parameters are global or if each execution path has their own counts (TODO). If each path holds their own counts then it would become `fanuc/{machine}/numberOfPieces/1`, `fanuc/{machine}/numberOfPieces/2`, ...
> 
> ```cs
> await Peel("numberOfPieces",
>     await SetNative("produced", await platform.RdParamDoubleWordNoAxisAsync(6711)),
>     await SetNative("producedLife", await platform.RdParamDoubleWordNoAxisAsync(6712)),
>     await SetNative("remaining", await platform.RdParamDoubleWordNoAxisAsync(6713)));
> ```

  - we can already gather the following data, but it would be nice to publish them in a single packet:
    - `fanuc/{machine}/6711/{path}` (number of pieces produced);
    - `fanuc/{machine}/6713/{path}` (number of pieces to be produced)
    - `fanuc/{machine}/6712/{path}` (total number of pieces produced);
  - note that on the only 2-path machine I have access to, on path 2, all three values (`6711-6713`) are equal to `0`, therefore I only need the values of path 1, but I cannot speak of all machines;, 

- currently executed program name (`cnc_rdprgnum` and `cnc_exeprgname`):
  - it might be a good idea to provide the times when a program is loaded (into memory), unloaded, started (`run`), stopped (error or waiting operators input), ended (finished the production of all pieces to be produced [`6713`]), but that all could be calculated outside of `fanuc-driver`);
- and possible any data related to the production (like program execution progress, etc).

**Comment by MRIIOT** [comment]
The `ThreeWay` collector accomplishes this.
