### ISSUE TITLE
Libs for armv7

### ISSUE THREAD

**Issue by SkaiBoa** [Ladder99/fanuc-driver#43]
Hi there,

I'm looking for the lib for 1.0.0 for armv7.

The lib libfwlib32-linux-armv7.so.1.0.5 works fine for me. But unfortunately functions that I need have been removed in this version.

Is there any way to get these libs: libfwlib32-linux-armv7.so.1.0.0 or libfwlib32-linux-armv7.so.1.0.1?

Many thanks in advance.

**Comment by MRIIOT** [comment]
I do not.  If you find it please let me know.

What functions are not working?
