### ISSUE TITLE
Using multiple strategy types

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#44]
@MRIIOT, can I use multiple strategy types in `config.yml`? Like `strategy: l99.driver.fanuc.collectors.UseCase01, l99.driver.fanuc.collectors.ProgramAndPieceCount, fanuc`? Or should I rather merge `l99.driver.fanuc.collectors.UseCase01` with `l99.driver.fanuc.collectors.ProgramAndPieceCount` first and then use the merged strategy type?

**Comment by MRIIOT** [comment]
Right now it is only one strategy type per machine.  Merging the strategies to give you the data you want would be ideal.

**Comment by tukusejssirs** [comment]
I see. Well, having multiple strategies is not that important then.
