### ISSUE TITLE
`fanuc-driver` versioning

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#47]
AFAIK, `fanuc-driver` does not have version number assigned, therefore I suggest to use [semantic versioning](https://semver.org/).

Related: #40 (this issue should be resolved prior to taking care of #40)

**Comment by MRIIOT** [comment]
Versioning between 0.1 and 0.5 hasn't been consistent with semantic versioning, because non-backward compatible changes have been made.  But I will keep this in mind going forward.
