### ISSUE TITLE
Supported Release

### ISSUE THREAD

**Issue by MRIIOT** [Ladder99/fanuc-driver#48]
Functionality towards releasing a supported release.

### External Interface

- [x] MQTT
- [x] SHDR
- [x] SparkplugB
- [ ] Database
- [ ] Interactive
- [ ] Diagnosis Dump
- [ ] Parameter Dump
- [ ] PMC Dump

### CNC Available

 - [x] Ability to connect to Fanuc Focas network port via TCP/IP.
 - [ ] Persist initialization to disk to prevent strategy startup from blocking.

### CNC Information

- [x] Type.
- [x] Model.
- [x] Series.
- [x] Version.
- [x] Number of execution paths.
- [x] Power on time.
- [x] Operating time.
- [x] Cutting time.
- [x] Active M codes.

### Operator Message

- [x] Implement collector.

### Emergency Stop

- [x] E-Stop flag.

## Axis Data

- [x] Number of axis and their names per execution path.
- [x] Diagnostics.

### Position

- [x] Absolute
- [x] Machine
- [x] Relative
- [x] Distance

### Load

- [x] Load percentage.
- [x] Power consumption.

### Actuator

- [ ] What actuator?

### Temperature

- [x] Servo temperature.
- [x] Encoder temperature.

### Overtravel

- [x] Implement collector.

## Spindle Data

- [x] Number of spindles and their names per execution path.
- [x] Motor temperature.
- [x] Encoder temperature.
- [x] Error
- [x] Warning
- [x] Encoder feedback.
- [x] Position loop deviation.
- [x] Synchronization error.
- [x] Spindle communication status and diagnostics.

### Spindle RPM

- [x] Spindle speed.
- [x] Maximum gear ratio.
- [x] Gear ratio.

### Spindle Load

- [x] Load percentage.
- [x] Power consumption.

### Spindle Override

- [x] Spindle override.

## Path Data

- [x] Path feedrate.
- [x] Feed override.
- [x] Rapid override.
- [x] Program execution line-by-line streaming.
- [x] Program name and number.
- [x] Program size.
- [x] Program comment.
- [x] Program modified date.
- [x] Current program block.
- [x] Current program line number.
- [x] Part cycle time.
- [x] Controller Mode
- [x] Execution State

### ToolID
 - [x] Tool number.

### Part Count
 - [x] Pieces produced.
 - [x] Pieces produced over lifetime.
 - [x] Pieces remaining.

## Alarms

- [x] All alarm categories.

**Comment by tukusejssirs** [comment]
A bit OT: I have another idea about alarms (and messages in general) in regards to `ThreeWay`: we could make the `alarms` an array of objects of the following structure:

```typescript
alarms = [
  {
    code: number,
    type: 'info' | 'pmc' | 'common' | 'program' | 'system',
    level: 'info' | 'warning' | 'error',
    message: string
  }
]
```

As for `level`, it is a nice-to-have thing. If it is not possible, then we could remove that property.

As for `type`, in the list above I have found following data, which could be assigned a `type` string:

- [`info`] Operator Message;
- [`pmc`] Logic Program (PMC Alarms);
- [`common`] Communications (CNC Common Alarms);
- [`program`] Motion Program (Part Program Alarms);
- [`system`] System (All other Alarms).

As a sidenote, even Mazaks have some similar division; these Mazak alarm types are all I could gather until now (I didn’t found yet an alarm specification nor did I really looked for it; maybe I even already have some manual with them):
- `MACHINE`;
- `NC`;
- `OPERATE`;
- `PROGRAM`;
- `SERVO`;
- `SPINDLE`;
- `SYSTEM`;
- `TRANSFER`.

**Comment by MRIIOT** [comment]
Supported since 0.6.
