### ISSUE TITLE
Republish latest messages on each topic on (re-) connection with the MQTT broker

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#59]
When the MQTT broker restarts, `fanuc-driver` will reconnect, but the broker doesn’t know about the retained messages. Republishing the latest messages on (re-) connection with the broker will fix this issue.

**Comment by MRIIOT** [comment]
Yes, when the broker is restarted, all retained messages are gone.

Could mosquitto persistence take care of this instead? https://mosquitto.org/man/mosquitto-conf-5.html

**Comment by MRIIOT** [comment]
We should test a couple scenarios and whether mosquitto built-in functionality will solve this before forcing the driver to re-publish.

https://github.com/eclipse/mosquitto/issues/769

**Comment by MRIIOT** [comment]
Can reopen after exhausting broker ways to handle this.
