### ISSUE TITLE
Not able to run the Fanuc docker image

### ISSUE THREAD

**Issue by anilsagar** [Ladder99/fanuc-driver#65]
Hi, 

I have followed the instructions of installing Fanuc docker image from [here ](https://docs.ladder99.com/en/latest/page/drivers/fanuc/installation-docker.html#clone-repository) but still getting an error that Fanuc container is not found. Could you pls suggest what could be the issue? 

Docker setup for ladder99 is already running in my machine. This machine is windows x64.

![image](https://user-images.githubusercontent.com/19199841/195559581-0bf79f3b-2a93-4646-9643-d9a06ccaffa4.png)

**Comment by tukusejssirs** [comment]
Did you build `fanuc-driver` (using `dotnet` v6+) and Docker container?

**Comment by anilsagar** [comment]
Yes I used .net 6. Found out the issue. Profile has to be set individually for admin, fanuc, mqtt and influx. So the whole set of commands has to be run 4 times. Once for each of these 4 individual profiles. Thanks for your support.
