### ISSUE TITLE
Broker connection failed 'tcp://localhost:1883/example-mqtt' unable to login on mqtt server

### ISSUE THREAD

**Issue by dineshkumarvfx** [Ladder99/fanuc-driver#66]
Am struck in this log and unable to view the data in mqtt.

**Comment by MRIIOT** [comment]
@dineshkumarvfx Is there a broker running at localhost:1883? What is localhost?

**Comment by dineshkumarvfx** [comment]
The local host is Windows based. Added an exception in firewall for MQTT then, issue for resolved. Thank you. One more doubt, how many fanuc machines can be connected via this driver?

**Comment by MRIIOT** [comment]
A hundred data points takes up 20% of CPU.  So 5 machines would consume a single CPU.
