### ISSUE TITLE
PartCount does not work 

### ISSUE THREAD

**Issue by Juanma2704** [Ladder99/fanuc-driver#84]
Hello Mr.IIot,
I have configured the fanuc driver in my device and connected a Fanuc 0i-D. Everything seems to work fine except the part count. It always shows like only 1 part has been produced. What could cause this issue?

**Comment by MRIIOT** [comment]
@Juanma2704 It depends on the GCode program and your NC configuration.

https://www.cnczone.com/forums/fanuc/153145-parameter-problems-part-count-working.html
