### ISSUE TITLE
Could we keep published Docker images indefinitely?

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#90]
Currently, it seems like you delete all but latest 2-3 images per architecture. However, when I use a particular `fanuc-driver` image version in a client app Docker compose file, after some time I am forced to upgrade to a newer (latest) `fanuc-driver` version unless I have the old image version already downloaded.

Reason why I want to stick to a particular `fanuc-driver` version is that you do many breaking changes without ever stating them in a release log or something. Recently, I had to upgrade from `linux64-develop-717424f` to `linux64-9e55095` and now to `linux64-f905690`. I had to manually compare the `fanuc-driver` configs and check if anything changed.

Is there any reason why you delete older images?

**Comment by MRIIOT** [comment]
Yes I can keep them around.
