### ISSUE TITLE
Ladder99/fanuc-driver - framework tried is .net core 3.1( x86). faced issue- got the error Unexpected Runtimeid 'win10x86'.

### ISSUE THREAD

**Issue by ajenita** [Ladder99/fanuc-driver#98]
Please suggest me to run the code

**Comment by MRIIOT** [comment]
Can you please attach logs or screenshots of the issue?

**Comment by ottobolyos** [comment]
I presume the issue is related to the fact that `fanuc-driver` recently upgraded its .NET to v7 (see [this commit](https://github.com/Ladder99/fanuc-driver/commit/9e55095bdacee7eb3129dcc5a0d078d6e3ceaf4d)).

**Comment by ajenita** [comment]
With dotnet runtime and sdk (version 7.0) I got the same issue unexpected runtimeid "win10x86"

**Comment by MRIIOT** [comment]
Need more information (logs, screenshots, etc).  If you can provide this information, then reopen the issue.

**Comment by ajenita** [comment]
![image](https://github.com/Ladder99/fanuc-driver/assets/142605018/28174f7d-f16f-46b2-b286-dcd020b2c11b)

Attached screenshot is my issue while building code in visual studio code. please provide suggestion to overcome this.

**Comment by MRIIOT** [comment]
@ajenita This sounds like a VS Code issue.  I really do not know.
